# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f5384d32e2c9f19d27230b99bc8e6a8eb99d0f20361afa7ea0c3ebcda17a816ab3d5fedcea693ad92b70ed1efae95d58ddc8433a91ea371a1569e1f970e9b18

test:
  secret_key_base: 0943fe503944f3711090257c7debd10c05b412f7372d8dac70469c7cdcc5c84f2a855aa09b26a6694f752e90566dad8d58e28c24bb3457a1220d457df1b91598

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
